Mercure refresh token
keicreations/sapphire-vue pull request #1
Opened 2020-03-30 15:51 UTC by alexkramer98

2020-03-30 15:59 UTC, martijnhartlief requested changes

2020-03-30 15:59 UTC, martijnhartlief commented on store/modules/mercure.js
> +                }).then(() => {
Please use the mercure module instead of the root

2020-03-30 15:59 UTC, martijnhartlief commented on store/modules/mercure.js
>              }
Duplicate code, single function please

2020-03-31 09:40 UTC, alexkramer98 commented
Apologies, everything should now be up to standard.

2020-03-31 09:50 UTC, merged